import { pathToFileURL } from 'node:url';
import { generateJson } from '../lib/generateJson.js';
import { config } from '../config.js';
import { APPROVED_VITAMIN_C_CLAIM_BG, APPROVED_VITAMIN_C_CLAIM_EN } from '../lib/regulatory.js';

// Luna audits — it never sees the writing prompt and never wrote the copy
// itself. It only ever sees the finished article text, same as a human
// reviewer would.
const LUNA_SYSTEM_PROMPT = `
You are an independent regulatory compliance auditor for CollagenLab, a Bulgarian/EU
e-commerce store selling collagen peptide food supplements. You did NOT write the article
under review — you are a separate, independent auditor checking finished copy against EU
Regulation (EC) No 1924/2006 on nutrition and health claims made on foods.

Scan the ENTIRE article — both the English text and the Bulgarian text — and flag every
violation you find. Assess the en and bg content separately; a violation may exist in one
language and not the other. Both languages are published, independently, and both must pass.

SEVERITY RULES:

HIGH severity:
- Disease treatment / cure / prevention claims (e.g. "лекува", "предотвратява болест",
  "cures", "treats", "prevents [disease]").
- Attributing specific health outcomes to collagen as an established fact (not hedged).
- An unauthorised health claim presented as if it were an authorised one.

MEDIUM severity:
- Implied medical benefits without hedging language.
- Claiming the product is "безопасно за всички" / "suitable for everyone".

LOW severity:
- The mandatory "food supplements are not a substitute for a varied diet and a healthy
  lifestyle" disclaimer is missing.
- The vitamin C claim is present but worded slightly differently from the authorised
  wording.
- Vague efficacy implications that are minor but worth a human's attention.

NOT a violation — do not flag these:
- Describing collagen's biological role (structural protein in skin, cartilage,
  connective tissue).
- Hedged, educational statements ("може да", "според някои изследвания", "may", "some
  studies suggest").
- A correctly-attributed vitamin C claim ("${APPROVED_VITAMIN_C_CLAIM_BG}" in Bulgarian, or
  "${APPROVED_VITAMIN_C_CLAIM_EN}" in English).

OUTPUT FORMAT: Respond with STRICT JSON only — no markdown code fences, no commentary
before or after. The JSON object must have exactly these keys:
{
  "passed": boolean,
  "flags": [
    {
      "severity": "high" | "medium" | "low",
      "language": "bg" | "en",
      "quote": string,
      "reason": string,
      "rule": string
    }
  ]
}
If you find no violations at all, return "passed": true and "flags": [].
`.trim();

function buildAuditPrompt(article) {
  return [
    '=== ENGLISH (en) ===',
    `Title: ${article.title_en}`,
    `Meta description: ${article.meta_en}`,
    `Summary: ${article.summary_en}`,
    'Body (HTML):',
    article.body_en_html,
    '',
    '=== BULGARIAN (bg) ===',
    `Title: ${article.title_bg}`,
    `Meta description: ${article.meta_bg}`,
    `Summary: ${article.summary_bg}`,
    'Body (HTML):',
    article.body_bg_html,
  ].join('\n');
}

async function runLunaAudit(article) {
  return generateJson({
    model: config.openai.models.luna,
    system: LUNA_SYSTEM_PROMPT,
    prompt: buildAuditPrompt(article),
  });
}

// article: the object returned by writeArticle()
// TODO: once a CollagenLab-specific approved-claim list exists, feed it into
// LUNA_SYSTEM_PROMPT so Luna checks against exact approved phrasing rather
// than the general EC 1924/2006 categories.
export async function checkCompliance(article) {
  const mode = config.pipeline.complianceMode;

  if (mode === 'off') {
    return { passed: true, flags: [] };
  }

  const audit = await runLunaAudit(article);
  const flags = Array.isArray(audit.flags) ? audit.flags : [];

  if (mode === 'log') {
    return { passed: true, flags };
  }

  // mode === 'block': only a HIGH-severity flag blocks publishing. The
  // policy decision lives here (not in Luna's own "passed" opinion) so it
  // stays consistent regardless of what the model thinks its verdict should be.
  const hasHighFlag = flags.some((flag) => flag.severity === 'high');
  return { passed: !hasHighFlag, flags };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  // The exact "колаген за кожа" article generated by writeArticle.js in the
  // prior step, used here as a fixed fixture so this step can be reviewed
  // independently of a live writeArticle.js run.
  const testArticle = {
    title_bg: 'Колаген за кожа: ползи, научна информация и информиран избор',
    meta_bg:
      'Колаген за кожа: научна информация за колагеновите пептиди, ролята на витамин C и как да избирате хранителна добавка.',
    body_bg_html:
      `<h2>Какво представлява колагенът и каква е ролята му за кожата?</h2><p>Колагенът е структурен белтък, който естествено се среща в човешкото тяло. Той участва в изграждането на съединителната тъкан, включително в кожата, костите, хрущялите, сухожилията и кръвоносните съдове. В кожата колагеновите влакна са част от нейната поддържаща структура заедно с други компоненти, като еластин и хиалуронова киселина.</p><p>С възрастта естественият синтез на колаген в организма намалява. Върху състоянието на кожата влияят и множество ежедневни фактори: излагане на слънце, тютюнопушене, хранене, сън, стрес, хидратация и индивидуални особености. Затова темата „колаген за кожа" често се разглежда като част от по-широк подход към грижата за външния вид и балансирания начин на живот, а не като самостоятелно решение.</p><h2>Какво са колагеновите пептиди?</h2><p>Колагеновите пептиди са получени чрез ензимна обработка на колаген, при която големите белтъчни молекули се разграждат до по-малки вериги от аминокиселини. Те обичайно се използват в хранителни добавки под формата на прах, сашета, капсули или готови напитки. Хидролизираният колаген е популярен именно заради удобството си за прием и добрата разтворимост в течности.</p><p>След прием белтъците и пептидите се разграждат и усвояват в храносмилателната система. Организмът използва аминокиселините според текущите си нужди. Важно е да се прави разлика между биологичната роля на колагена в тялото и конкретните маркетингови обещания за хранителна добавка: колагеновите пептиди сами по себе си нямат одобрена здравна претенция в Европейския съюз за състоянието на кожата.</p><h2>Какво разглежда научната литература?</h2><p>Научните публикации за пероралните колагенови пептиди проучват различни показатели, свързани с кожата, включително хидратация, еластичност и вид на фините линии. Някои изследвания отчитат промени при определени групи участници след редовен прием за конкретен период. Тези данни обаче трябва да се тълкуват внимателно.</p><p>Резултатите между отделните проучвания не винаги са пряко сравними. Различават се видът и произходът на използваните пептиди, количествата, продължителността, възрастта и навиците на участниците, както и методите за измерване. Част от изследванията са с малък брой участници или са финансирани от производители. Поради това отделен резултат не е гаранция за индивидуален ефект и не бива да се приема като обещание за промяна на кожата.</p><h3>Морски, говежди и други източници</h3><p>На етикета на продуктите може да бъде посочен произходът на колагена – например морски, говежди или свински. Те се различават по суровина и профил на пептидите. Изборът често зависи от личните предпочитания, хранителния режим, наличието на алергии и прозрачността на производителя относно състава и произхода. При морски колаген е особено важно хората с алергия към риба да проверят информацията върху опаковката.</p><h2>Витамин C и нормалното образуване на колаген</h2><p>Витамин C има специфична и призната роля в този контекст. ${APPROVED_VITAMIN_C_CLAIM_BG} Това е одобрена здравна претенция за витамин C, а не за колагеновите пептиди.</p><p>Витамин C се съдържа в много плодове и зеленчуци, например цитруси, киви, ягоди, чушки, броколи и зеле. Разнообразното меню е практичен начин да се включват източници на този витамин наред с белтъчини, полезни мазнини и други хранителни вещества.</p><h2>Как да изберете колаген за кожа?</h2><p>Когато разглеждате хранителна добавка с колаген, фокусирайте се върху ясната информация, а не само върху рекламното послание. Добре е да проверите пълния списък със съставки, произхода на колагена, формата на продукта и наличието на подсладители, ароматизанти или допълнителни активни вещества.</p><ul><li>Проверете количеството колагенови пептиди, посочено за препоръчителния дневен прием.</li><li>Изберете продукт с ясен етикет, партиден номер и данни за производителя или вносителя.</li><li>Ако продуктът съдържа витамин C, разгледайте общото си хранене и останалите добавки, които приемате.</li><li>Вземете предвид алергии, бременност, кърмене, хронични състояния и лекарства; при съмнение се консултирайте с лекар или фармацевт.</li><li>Следвайте указанията на етикета и не превишавайте препоръчителния дневен прием.</li></ul><h2>Реалистичен подход към грижата за кожата</h2><p>Колагенът за кожа може да бъде тема на информиран личен избор, но не заменя основните навици. Ежедневната фотозащита, щадящата козметична грижа, достатъчният сън, приемът на разнообразна храна и ограничаването на тютюнопушенето са важни елементи от цялостния подход към кожата. При внезапни, трайни или притеснителни кожни промени най-разумната стъпка е консултацията с дерматолог.</p><p>Хранителните добавки не са заместител на разнообразното хранене и здравословния начин на живот.</p>`,
    summary_bg:
      'Колагенът е структурен белтък в кожата и съединителната тъкан, а колагеновите пептиди са често използвана съставка в хранителни добавки. Научните данни се проучват активно, но информираният избор включва реалистични очаквания, ясен състав и балансиран начин на живот.',
    title_en: 'Collagen for Skin: Science, Types and How to Choose Wisely',
    meta_en:
      'Collagen for skin: what the science says about collagen peptides, the role of vitamin C, and how to choose a supplement.',
    body_en_html:
      `<h2>What is collagen and what role does it play in the skin?</h2><p>Collagen is a structural protein that occurs naturally in the human body. It is involved in the structure of connective tissues, including the skin, bones, cartilage, tendons and blood vessels. Within the skin, collagen fibres form part of its supportive framework alongside components such as elastin and hyaluronic acid.</p><p>Natural collagen production declines with age. Skin appearance is also influenced by many everyday factors, including sun exposure, smoking, diet, sleep, stress, hydration and individual characteristics. For this reason, collagen for skin is best considered within a broader approach to skincare, wellbeing and a balanced lifestyle—not as a stand-alone solution.</p><h2>What are collagen peptides?</h2><p>Collagen peptides are produced through enzymatic processing, which breaks larger collagen proteins into smaller chains of amino acids. They are commonly used in food supplements in powder, sachet, capsule and ready-to-drink formats. Hydrolysed collagen is popular largely because it is convenient to take and dissolves readily in liquids.</p><p>After consumption, proteins and peptides are digested and absorbed by the body. The body uses amino acids according to its current needs. It is important to distinguish collagen's biological role in the body from product marketing claims: collagen peptides do not have an authorised EU health claim for skin condition.</p><h2>What does the scientific literature examine?</h2><p>Research on oral collagen peptides has explored a range of skin-related measures, including hydration, elasticity and the appearance of fine lines. Some studies have reported changes in specific groups of participants after regular use over a defined period. However, these findings should be interpreted with care.</p><p>Results from individual studies are not always directly comparable. The type and source of peptides, quantities used, study duration, participants' ages and lifestyles, and measurement methods can all differ. Some studies also involve small participant numbers or manufacturer funding. A result observed in one study is therefore not a guarantee of an individual outcome or a promise of change in the skin.</p><h3>Marine, bovine and other sources</h3><p>Product labels may identify the source of collagen, such as marine, bovine or porcine. These sources differ in their raw materials and peptide profiles. The right choice often depends on personal preferences, dietary requirements, allergies and how transparently the manufacturer presents its ingredients and sourcing. Anyone with a fish allergy should check marine collagen product information particularly carefully.</p><h2>Vitamin C and normal collagen formation</h2><p>Vitamin C has a specific, recognised role in this context. ${APPROVED_VITAMIN_C_CLAIM_EN} This is an authorised health claim for vitamin C, rather than for collagen peptides.</p><p>Vitamin C is found in many fruits and vegetables, including citrus fruits, kiwis, strawberries, peppers, broccoli and cabbage. A varied diet is a practical way to include sources of this vitamin alongside protein, beneficial fats and other nutrients.</p><h2>How to choose a collagen supplement for skin</h2><p>When considering a collagen food supplement, focus on clear product information rather than advertising alone. Check the full ingredient list, collagen source, product format, and whether it contains sweeteners, flavourings or additional active ingredients.</p><ul><li>Check the amount of collagen peptides provided in the recommended daily serving.</li><li>Choose a product with a clear label, batch number and manufacturer or importer details.</li><li>If the product contains vitamin C, consider your overall diet and any other supplements you take.</li><li>Take allergies, pregnancy, breastfeeding, ongoing health conditions and medicines into account. If in doubt, speak to a doctor or pharmacist.</li><li>Follow the label instructions and do not exceed the recommended daily intake.</li></ul><h2>A realistic approach to skin care</h2><p>Collagen for skin can be a topic for an informed personal choice, but it does not replace everyday foundations. Daily sun protection, gentle skincare, adequate sleep, a varied diet and avoiding smoking are all important parts of a comprehensive approach to skin health. For sudden, persistent or concerning changes to the skin, consulting a dermatologist is the most sensible next step.</p><p>Food supplements should not be used as a substitute for a varied diet and a healthy lifestyle.</p>`,
    summary_en:
      'Collagen is a structural protein found in skin and connective tissue, and collagen peptides are a common supplement ingredient. The evidence is actively studied, and an informed choice means realistic expectations, a clear ingredient list, and a balanced lifestyle.',
  };

  checkCompliance(testArticle)
    .then((result) => {
      console.log(JSON.stringify(result, null, 2));
      process.exit(0);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
